# Generated by Django 5.2.7 on 2025-11-04 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('policy_type', models.CharField(choices=[('individual', 'Individual'), ('family', 'Family'), ('employer', 'Employer Sponsored'), ('ngo', 'NGO Supported'), ('health', 'Health Policy')], max_length=20)),
                ('coverage_details', models.TextField(blank=True, null=True)),
                ('premium', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_claim_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('waiting_period_days', models.PositiveIntegerField(default=0)),
                ('deductible', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shariah_approved', models.BooleanField(default=False, help_text='Approved by Shariah board')),
                ('shariah_review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
