# Generated by Django 5.2.7 on 2025-11-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='shariah_approved',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='shariah_review_notes',
        ),
    ]
