# Generated by Django 5.2.7 on 2025-10-25 03:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_hospitalassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={},
        ),
        migrations.RemoveField(
            model_name='policy',
            name='deductible',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='policy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='policy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('health', 'Health'), ('life', 'Life'), ('auto', 'Auto'), ('home', 'Home')], max_length=50),
        ),
        migrations.AlterField(
            model_name='policy',
            name='premium',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='policy',
            name='waiting_period_days',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='HospitalAssignment',
        ),
    ]
