# Generated by Django 5.2.7 on 2025-10-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_alter_policy_options_remove_policy_deductible_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='policy',
            name='deductible',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='policy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('family', 'Family'), ('employer', 'Employer Sponsored'), ('ngo', 'NGO Supported'), ('health', 'Health Policy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='policy',
            name='premium',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='policy',
            name='waiting_period_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
