# Generated by Django 5.2.7 on 2025-11-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_insuredperson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuredperson',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='insuredperson',
            name='fingerprint_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuredperson',
            name='fingerprint_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='relationship',
            field=models.CharField(max_length=50),
        ),
    ]
