# Generated by Django 5.2.7 on 2025-11-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_alter_insuredperson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredperson',
            name='id_card_generated',
            field=models.BooleanField(default=False),
        ),
    ]
