# Generated by Django 5.2.7 on 2025-11-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_insuredperson_id_card_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuredperson',
            name='id_card_generated',
        ),
    ]
