# Generated by Django 5.2.7 on 2025-11-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_remove_insuredperson_id_card_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='coverage_level',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20),
        ),
        migrations.AddField(
            model_name='policy',
            name='nric_or_passport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='payment_mode',
            field=models.CharField(choices=[('annual', 'Annual'), ('semi_annual', 'Semi-Annual'), ('monthly', 'Monthly')], default='annual', max_length=20),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
    ]
