# Generated by Django 5.2.7 on 2025-11-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_policy_coverage_level_policy_nric_or_passport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
