# Generated by Django 5.2.7 on 2025-11-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0008_policy_address_policy_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='address',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='contact',
        ),
        migrations.AlterField(
            model_name='policy',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('family', 'Family'), ('employer', 'Employer Sponsored'), ('ngo', 'NGO Supported'), ('health', 'Health Policy')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='policy',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
    ]
