# Generated by Django 5.2.7 on 2026-01-20 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_nric_or_passport'),
        ('policies', '0009_remove_policy_address_remove_policy_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='expiry_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['policy_number'], name='policies_po_policy__a03f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['expiry_date'], name='policies_po_expiry__9bb999_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['is_active', 'is_archived'], name='policies_po_is_acti_2c96cf_idx'),
        ),
    ]
