# Generated by Django 5.2.7 on 2026-01-26 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_initial'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_claims', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('male_clients', models.PositiveIntegerField(default=0)),
                ('female_clients', models.PositiveIntegerField(default=0)),
                ('age_0_18', models.PositiveIntegerField(default=0)),
                ('age_19_35', models.PositiveIntegerField(default=0)),
                ('age_36_60', models.PositiveIntegerField(default=0)),
                ('age_60_plus', models.PositiveIntegerField(default=0)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'hospital')},
            },
        ),
    ]
