# Generated by Django 5.2.7 on 2026-01-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_populationhealth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopulationHealth',
        ),
    ]
