# Generated by Django 5.2.7 on 2026-01-27 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_delete_populationhealth'),
        ('clients', '0002_client_nric_or_passport'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('ANC', 'Antenatal Care'), ('DELIVERY', 'Delivery'), ('PNC', 'Postnatal Care'), ('OTHER', 'Other')], max_length=20)),
                ('event_datetime', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='manual_entry', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_events', to='claims.claim')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital')),
            ],
            options={
                'ordering': ['-event_datetime'],
            },
        ),
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='claims.clinicalevent')),
            ],
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('maternal', 'Maternal'), ('neonatal', 'Neonatal')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='claims.clinicalevent')),
            ],
        ),
    ]
