# Generated by Django 5.2.7 on 2026-01-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_clinicalevent_healthmetric_riskscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmetric',
            name='category',
            field=models.CharField(blank=True, choices=[('maternal', 'Maternal'), ('delivery', 'Delivery'), ('postnatal', 'Postnatal'), ('facility', 'Facility'), ('risk', 'Risk')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20),
        ),
    ]
