# Generated by Django 5.2.7 on 2026-01-31 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_alter_healthmetric_category_alter_riskscore_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin / Claim Officer / Finance who approved the claim', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='shariah_approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved claim from Shariah board', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shariah_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
