# Generated by Django 5.2.7 on 2026-02-01 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_claim_approved_at_claim_approved_by_and_more'),
        ('policies', '0012_alter_policyaudit_performed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalevent',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_events', to='policies.insuredperson'),
        ),
    ]
