# Generated by Django 5.2.7 on 2026-02-01 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_clinicalevent_patient'),
        ('clients', '0004_remove_client_secure_token_and_more'),
        ('hospitals', '0001_initial'),
        ('policies', '0012_alter_policyaudit_performed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='policies.insuredperson'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claim',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='hospitals.hospital'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='policies.policy'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='shariah_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='claim',
            name='shariah_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shariah_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinicalevent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_events', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='clinicalevent',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_events', to='hospitals.hospital'),
        ),
    ]
