# Generated by Django 5.2.7 on 2026-01-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nric_or_passport',
            field=models.CharField(blank=True, help_text='National ID / Passport Number', max_length=50, null=True),
        ),
    ]
