# Generated by Django 5.2.7 on 2026-01-29 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_nric_or_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='secure_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='ClientVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to='clients.client')),
            ],
        ),
    ]
