# Generated by Django 5.2.7 on 2026-02-01 23:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_secure_token_clientverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='secure_token',
        ),
        migrations.AlterField(
            model_name='client',
            name='nric_or_passport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter valid phone number')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='shariah_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('patient_type', models.CharField(choices=[('child', 'Child'), ('maternal', 'Maternal')], default='child', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
