# Generated by Django 5.2.7 on 2025-11-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shariah_approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shariah_review_notes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('agent', 'Agent'), ('policyholder', 'Policyholder'), ('claim_officer', 'Claim Officer'), ('finance_officer', 'Finance Officer'), ('report_officer', 'Report Officer'), ('hospital', 'Hospital')], default='policyholder', help_text='Role of the user in the system', max_length=20),
        ),
    ]
