# Generated by Django 5.2.7 on 2025-12-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_completed_at_task_priority_alter_task_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['week', 'due_date', 'status']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_at',
        ),
    ]
