# Generated by Django 5.2.7 on 2025-10-25 03:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('hospitals', '0001_initial'),
        ('policies', '0003_alter_policy_options_remove_policy_deductible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hospitals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HospitalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hospital_tasks', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_assignments', to='clients.client')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_clients', to='hospitals.hospital')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_assignments', to='policies.policy')),
            ],
        ),
    ]
