# Generated by Django 5.2.7 on 2025-10-26 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
        ('hospitals', '0002_alter_hospital_created_by_hospitalassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalassignment',
            name='claim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='claims.claim'),
        ),
        migrations.AlterField(
            model_name='hospitalassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('claimed', 'Claim Submitted'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
